// <auto-generated />
namespace NewVidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewModel_Genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewModel_Genre));
        
        string IMigrationMetadata.Id
        {
            get { return "202003311013182_NewModel_Genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
